#pragma once

#define TAPPING_TERM 200

#define IGNORE_MOD_TAP_INTERRUPT

#define HOLD_ON_OTHER_KEY_PRESS

#define PERMISSIVE_HOLD
/* #define PERMISSIVE_HOLD_PER_KEY */
/* #define TAPPING_TERM_PER_KEY */
/* #define LONG_TAPPING_TERM 1250 */

#define AUTO_SHIFT_TIMEOUT 130
#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_TIMEOUT_PER_KEY

#define CAPS_WORD_IDLE_TIMEOUT 1500

#define MOUSEKEY_WHEEL_DELAY 300
/* #define MOUSEKEY_WHEEL_MAX_SPEED 1 */

#define COMBO_COUNT 7

#define ONESHOT_TIMEOUT 2000
#define ONESHOT_TAP_TOGGLE 5
